############# English navigation ##############

# main menu
[[main]]
name = "Resources"
weight = 1

[[main]]
parent = "Resources"
name = "Neuromorphic Computing"
url = "/neuromorphic-computing/"
weight = 2

[[main]]
parent = "Resources"
name = "Neuromorphic Hardware"
url = "/neuromorphic-computing/hardware"
weight = 2

[[main]]
parent = "Resources"
name = "Neuromorphic Software"
url = "/neuromorphic-computing/software"
weight = 2

[[main]]
name = "Workshops"
url = "/workshops/"
weight = 3

[[main]]
name = "Blog"
url = "/blog/"
weight = 4

[[main]]
name = "About"
hasChildren = true
weight = 5

[[main]]
parent = "About"
name = "About Open Neuromorphic"
url = "/about/"
weight = 1

[[main]]
parent = "About"
name = "Getting Involved"
url = "/getting-involved/"
weight = 2

[[main]]
parent = "About"
name = "Organizers"
url = "/team/"
weight = 3

[[main]]
parent = "About"
name = "Contributors"
url = "/contributors/"
weight = 5

# [[main]]
# parent = "About"
# name = "Advisers"
# url = "/advisers/"
# weight = 6

# footer menu
[[footer]]
name = "Quick Links"
hasChildren = true

[[footer]]
parent = "Quick Links"
name = "Organizers"
url = "/team/"
weight = 2

[[footer]]
parent = "Quick Links"
name = "Contributors"
url = "/contributors/"
weight = 3

[[footer]]
parent = "Quick Links"
name = "Join Our Discord"
url = "https://discord.gg/C9bzWgNmqk"
weight = 4

[[footer]]
parent = "Quick Links"
name = "How to Get Involved"
url = "/getting-involved/"
weight = 1



